import "@/app/globals.css";
import { NextAuthProvider } from "@/app/providers/NextAuthProvider";
import { Montserrat } from "next/font/google";

const fontFamily = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body
          className={
            fontFamily.className +
            ""
          }
        >
          <main className="">{children}</main>
        </body>
      </NextAuthProvider>
    </html >
  );
}
